package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePassportUseraccesslog<M extends BasePassportUseraccesslog<M>> extends Model<M> implements IBean {

	public void setAccessLogID(java.lang.String AccessLogID) {
		set("AccessLogID", AccessLogID);
	}

	public java.lang.String getAccessLogID() {
		return get("AccessLogID");
	}

	public void setUserID(java.lang.Integer UserID) {
		set("UserID", UserID);
	}

	public java.lang.Integer getUserID() {
		return get("UserID");
	}

	public void setLastLoginDate(java.util.Date LastLoginDate) {
		set("LastLoginDate", LastLoginDate);
	}

	public java.util.Date getLastLoginDate() {
		return get("LastLoginDate");
	}

	public void setFailedPasswordAttemptCount(java.lang.Integer FailedPasswordAttemptCount) {
		set("FailedPasswordAttemptCount", FailedPasswordAttemptCount);
	}

	public java.lang.Integer getFailedPasswordAttemptCount() {
		return get("FailedPasswordAttemptCount");
	}

	public void setFailedPasswordAttemptStart(java.util.Date FailedPasswordAttemptStart) {
		set("FailedPasswordAttemptStart", FailedPasswordAttemptStart);
	}

	public java.util.Date getFailedPasswordAttemptStart() {
		return get("FailedPasswordAttemptStart");
	}

	public void setModifyTime(java.util.Date ModifyTime) {
		set("ModifyTime", ModifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("ModifyTime");
	}

}
