package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtMenu<M extends BasePtMenu<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setImages(java.lang.String images) {
		set("images", images);
	}

	public java.lang.String getImages() {
		return get("images");
	}

	public void setLevels(java.lang.Long levels) {
		set("levels", levels);
	}

	public java.lang.Long getLevels() {
		return get("levels");
	}

	public void setOrderids(java.lang.Long orderids) {
		set("orderids", orderids);
	}

	public java.lang.Long getOrderids() {
		return get("orderids");
	}

	public void setOperatorids(java.lang.String operatorids) {
		set("operatorids", operatorids);
	}

	public java.lang.String getOperatorids() {
		return get("operatorids");
	}

	public void setParentmenuids(java.lang.String parentmenuids) {
		set("parentmenuids", parentmenuids);
	}

	public java.lang.String getParentmenuids() {
		return get("parentmenuids");
	}

	public void setSystemsids(java.lang.String systemsids) {
		set("systemsids", systemsids);
	}

	public java.lang.String getSystemsids() {
		return get("systemsids");
	}

	public void setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public void setNamesZhcn(java.lang.String namesZhcn) {
		set("names_zhcn", namesZhcn);
	}

	public java.lang.String getNamesZhcn() {
		return get("names_zhcn");
	}

	public void setNamesZhhk(java.lang.String namesZhhk) {
		set("names_zhhk", namesZhhk);
	}

	public java.lang.String getNamesZhhk() {
		return get("names_zhhk");
	}

	public void setNamesZhtw(java.lang.String namesZhtw) {
		set("names_zhtw", namesZhtw);
	}

	public java.lang.String getNamesZhtw() {
		return get("names_zhtw");
	}

	public void setNamesEnus(java.lang.String namesEnus) {
		set("names_enus", namesEnus);
	}

	public java.lang.String getNamesEnus() {
		return get("names_enus");
	}

	public void setNamesJa(java.lang.String namesJa) {
		set("names_ja", namesJa);
	}

	public java.lang.String getNamesJa() {
		return get("names_ja");
	}

	public void setParam(java.lang.String param) {
		set("param", param);
	}

	public java.lang.String getParam() {
		return get("param");
	}

}
