package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtSyslog<M extends BasePtSyslog<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setActionenddate(java.util.Date actionenddate) {
		set("actionenddate", actionenddate);
	}

	public java.util.Date getActionenddate() {
		return get("actionenddate");
	}

	public void setActionendtime(java.lang.Long actionendtime) {
		set("actionendtime", actionendtime);
	}

	public java.lang.Long getActionendtime() {
		return get("actionendtime");
	}

	public void setActionhaoshi(java.lang.Long actionhaoshi) {
		set("actionhaoshi", actionhaoshi);
	}

	public java.lang.Long getActionhaoshi() {
		return get("actionhaoshi");
	}

	public void setActionstartdate(java.util.Date actionstartdate) {
		set("actionstartdate", actionstartdate);
	}

	public java.util.Date getActionstartdate() {
		return get("actionstartdate");
	}

	public void setActionstarttime(java.lang.Long actionstarttime) {
		set("actionstarttime", actionstarttime);
	}

	public java.lang.Long getActionstarttime() {
		return get("actionstarttime");
	}

	public void setCause(java.lang.String cause) {
		set("cause", cause);
	}

	public java.lang.String getCause() {
		return get("cause");
	}

	public void setCookie(java.lang.String cookie) {
		set("cookie", cookie);
	}

	public java.lang.String getCookie() {
		return get("cookie");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setEnddate(java.util.Date enddate) {
		set("enddate", enddate);
	}

	public java.util.Date getEnddate() {
		return get("enddate");
	}

	public void setEndtime(java.lang.Long endtime) {
		set("endtime", endtime);
	}

	public java.lang.Long getEndtime() {
		return get("endtime");
	}

	public void setHaoshi(java.lang.Long haoshi) {
		set("haoshi", haoshi);
	}

	public java.lang.Long getHaoshi() {
		return get("haoshi");
	}

	public void setIps(java.lang.String ips) {
		set("ips", ips);
	}

	public java.lang.String getIps() {
		return get("ips");
	}

	public void setMethod(java.lang.String method) {
		set("method", method);
	}

	public java.lang.String getMethod() {
		return get("method");
	}

	public void setReferer(java.lang.String referer) {
		set("referer", referer);
	}

	public java.lang.String getReferer() {
		return get("referer");
	}

	public void setRequestpath(java.lang.String requestpath) {
		set("requestpath", requestpath);
	}

	public java.lang.String getRequestpath() {
		return get("requestpath");
	}

	public void setStartdate(java.util.Date startdate) {
		set("startdate", startdate);
	}

	public java.util.Date getStartdate() {
		return get("startdate");
	}

	public void setStarttime(java.lang.Long starttime) {
		set("starttime", starttime);
	}

	public java.lang.Long getStarttime() {
		return get("starttime");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setUseragent(java.lang.String useragent) {
		set("useragent", useragent);
	}

	public java.lang.String getUseragent() {
		return get("useragent");
	}

	public void setViewhaoshi(java.lang.Long viewhaoshi) {
		set("viewhaoshi", viewhaoshi);
	}

	public java.lang.Long getViewhaoshi() {
		return get("viewhaoshi");
	}

	public void setOperatorids(java.lang.String operatorids) {
		set("operatorids", operatorids);
	}

	public java.lang.String getOperatorids() {
		return get("operatorids");
	}

	public void setAccept(java.lang.String accept) {
		set("accept", accept);
	}

	public java.lang.String getAccept() {
		return get("accept");
	}

	public void setAcceptencoding(java.lang.String acceptencoding) {
		set("acceptencoding", acceptencoding);
	}

	public java.lang.String getAcceptencoding() {
		return get("acceptencoding");
	}

	public void setAcceptlanguage(java.lang.String acceptlanguage) {
		set("acceptlanguage", acceptlanguage);
	}

	public java.lang.String getAcceptlanguage() {
		return get("acceptlanguage");
	}

	public void setConnection(java.lang.String connection) {
		set("connection", connection);
	}

	public java.lang.String getConnection() {
		return get("connection");
	}

	public void setHost(java.lang.String host) {
		set("host", host);
	}

	public java.lang.String getHost() {
		return get("host");
	}

	public void setXrequestedwith(java.lang.String xrequestedwith) {
		set("xrequestedwith", xrequestedwith);
	}

	public java.lang.String getXrequestedwith() {
		return get("xrequestedwith");
	}

	public void setPvids(java.lang.String pvids) {
		set("pvids", pvids);
	}

	public java.lang.String getPvids() {
		return get("pvids");
	}

	public void setUserids(java.lang.String userids) {
		set("userids", userids);
	}

	public java.lang.String getUserids() {
		return get("userids");
	}

}
