package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtStation<M extends BasePtStation<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setImages(java.lang.String images) {
		set("images", images);
	}

	public java.lang.String getImages() {
		return get("images");
	}

	public void setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public void setNames(java.lang.String names) {
		set("names", names);
	}

	public java.lang.String getNames() {
		return get("names");
	}

	public void setOrderids(java.lang.Long orderids) {
		set("orderids", orderids);
	}

	public java.lang.Long getOrderids() {
		return get("orderids");
	}

	public void setParentstationids(java.lang.String parentstationids) {
		set("parentstationids", parentstationids);
	}

	public java.lang.String getParentstationids() {
		return get("parentstationids");
	}

}
