package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbcUserAnswer<M extends BaseAbcUserAnswer<M>> extends Model<M> implements IBean {

	public void setAnswerId(java.lang.Integer answerId) {
		set("answer_id", answerId);
	}

	public java.lang.Integer getAnswerId() {
		return get("answer_id");
	}

	public void setAnswerContent(java.lang.String answerContent) {
		set("answer_content", answerContent);
	}

	public java.lang.String getAnswerContent() {
		return get("answer_content");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("create_user");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateUser(java.lang.Integer updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.Integer getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setAnswerAudioUrl(java.lang.String answerAudioUrl) {
		set("answer_audio_url", answerAudioUrl);
	}

	public java.lang.String getAnswerAudioUrl() {
		return get("answer_audio_url");
	}

}
