package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtUsergroup<M extends BasePtUsergroup<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setUserids(java.lang.String userids) {
		set("userids", userids);
	}

	public java.lang.String getUserids() {
		return get("userids");
	}

	public void setGroupids(java.lang.String groupids) {
		set("groupids", groupids);
	}

	public java.lang.String getGroupids() {
		return get("groupids");
	}

}
