package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtStationoperator<M extends BasePtStationoperator<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setStationids(java.lang.String stationids) {
		set("stationids", stationids);
	}

	public java.lang.String getStationids() {
		return get("stationids");
	}

	public void setOperatorids(java.lang.String operatorids) {
		set("operatorids", operatorids);
	}

	public java.lang.String getOperatorids() {
		return get("operatorids");
	}

}
