package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtDict<M extends BasePtDict<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setImages(java.lang.String images) {
		set("images", images);
	}

	public java.lang.String getImages() {
		return get("images");
	}

	public void setNames(java.lang.String names) {
		set("names", names);
	}

	public java.lang.String getNames() {
		return get("names");
	}

	public void setOrderids(java.lang.Long orderids) {
		set("orderids", orderids);
	}

	public java.lang.Long getOrderids() {
		return get("orderids");
	}

	public void setPaths(java.lang.String paths) {
		set("paths", paths);
	}

	public java.lang.String getPaths() {
		return get("paths");
	}

	public void setZhuangtai(java.lang.String zhuangtai) {
		set("zhuangtai", zhuangtai);
	}

	public java.lang.String getZhuangtai() {
		return get("zhuangtai");
	}

	public void setParentids(java.lang.String parentids) {
		set("parentids", parentids);
	}

	public java.lang.String getParentids() {
		return get("parentids");
	}

	public void setIsparent(java.lang.String isparent) {
		set("isparent", isparent);
	}

	public java.lang.String getIsparent() {
		return get("isparent");
	}

	public void setLevels(java.lang.Long levels) {
		set("levels", levels);
	}

	public java.lang.Long getLevels() {
		return get("levels");
	}

	public void setNumbers(java.lang.String numbers) {
		set("numbers", numbers);
	}

	public java.lang.String getNumbers() {
		return get("numbers");
	}

	public void setVal(java.lang.String val) {
		set("val", val);
	}

	public java.lang.String getVal() {
		return get("val");
	}

	public void setI18n(java.lang.String i18n) {
		set("i18n", i18n);
	}

	public java.lang.String getI18n() {
		return get("i18n");
	}

	public void setValZhcn(java.lang.String valZhcn) {
		set("val_zhcn", valZhcn);
	}

	public java.lang.String getValZhcn() {
		return get("val_zhcn");
	}

	public void setValZhhk(java.lang.String valZhhk) {
		set("val_zhhk", valZhhk);
	}

	public java.lang.String getValZhhk() {
		return get("val_zhhk");
	}

	public void setValZhtw(java.lang.String valZhtw) {
		set("val_zhtw", valZhtw);
	}

	public java.lang.String getValZhtw() {
		return get("val_zhtw");
	}

	public void setValJa(java.lang.String valJa) {
		set("val_ja", valJa);
	}

	public java.lang.String getValJa() {
		return get("val_ja");
	}

	public void setValEnus(java.lang.String valEnus) {
		set("val_enus", valEnus);
	}

	public java.lang.String getValEnus() {
		return get("val_enus");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
