package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePtUpload<M extends BasePtUpload<M>> extends Model<M> implements IBean {

	public void setIds(java.lang.String ids) {
		set("ids", ids);
	}

	public java.lang.String getIds() {
		return get("ids");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setParametername(java.lang.String parametername) {
		set("parametername", parametername);
	}

	public java.lang.String getParametername() {
		return get("parametername");
	}

	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}

	public java.lang.String getFilename() {
		return get("filename");
	}

	public void setContenttype(java.lang.String contenttype) {
		set("contenttype", contenttype);
	}

	public java.lang.String getContenttype() {
		return get("contenttype");
	}

	public void setOriginalfilename(java.lang.String originalfilename) {
		set("originalfilename", originalfilename);
	}

	public java.lang.String getOriginalfilename() {
		return get("originalfilename");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}

	public java.lang.String getPath() {
		return get("path");
	}

	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}

	public java.lang.String getMd5() {
		return get("md5");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return get("describe");
	}

	public void setOrderids(java.lang.Long orderids) {
		set("orderids", orderids);
	}

	public java.lang.Long getOrderids() {
		return get("orderids");
	}

	public void setSize(java.lang.Long size) {
		set("size", size);
	}

	public java.lang.Long getSize() {
		return get("size");
	}

	public void setTargetids(java.lang.String targetids) {
		set("targetids", targetids);
	}

	public java.lang.String getTargetids() {
		return get("targetids");
	}

}
