package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbcResourceToQuestion<M extends BaseAbcResourceToQuestion<M>> extends Model<M> implements IBean {

	public void setRelationId(java.lang.Integer relationId) {
		set("relation_id", relationId);
	}

	public java.lang.Integer getRelationId() {
		return get("relation_id");
	}

	public void setQuesId(java.lang.Integer quesId) {
		set("ques_id", quesId);
	}

	public java.lang.Integer getQuesId() {
		return get("ques_id");
	}

	public void setResId(java.lang.Integer resId) {
		set("res_id", resId);
	}

	public java.lang.Integer getResId() {
		return get("res_id");
	}

	public void setResType(java.lang.Integer resType) {
		set("res_type", resType);
	}

	public java.lang.Integer getResType() {
		return get("res_type");
	}

	public void setResPosition(java.lang.String resPosition) {
		set("res_position", resPosition);
	}

	public java.lang.String getResPosition() {
		return get("res_position");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("create_user");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateUser(java.lang.Integer updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.Integer getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
