package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePassportSigninInfo<M extends BasePassportSigninInfo<M>> extends Model<M> implements IBean {

	public void setSigninId(java.lang.String signinId) {
		set("SIGNIN_ID", signinId);
	}

	public java.lang.String getSigninId() {
		return get("SIGNIN_ID");
	}

	public void setSortId(java.lang.Integer sortId) {
		set("SORT_ID", sortId);
	}

	public java.lang.Integer getSortId() {
		return get("SORT_ID");
	}

	public void setSigninTime(java.util.Date signinTime) {
		set("SIGNIN_TIME", signinTime);
	}

	public java.util.Date getSigninTime() {
		return get("SIGNIN_TIME");
	}

	public void setSigninTimeout(java.util.Date signinTimeout) {
		set("SIGNIN_TIMEOUT", signinTimeout);
	}

	public java.util.Date getSigninTimeout() {
		return get("SIGNIN_TIMEOUT");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}

	public java.lang.String getUserId() {
		return get("USER_ID");
	}

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}

	public java.lang.String getUserName() {
		return get("USER_NAME");
	}

	public void setDOMAIN(java.lang.String DOMAIN) {
		set("DOMAIN", DOMAIN);
	}

	public java.lang.String getDOMAIN() {
		return get("DOMAIN");
	}

	public void setAuthenticateServer(java.lang.String authenticateServer) {
		set("AUTHENTICATE_SERVER", authenticateServer);
	}

	public java.lang.String getAuthenticateServer() {
		return get("AUTHENTICATE_SERVER");
	}

}
