package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbcQuestion<M extends BaseAbcQuestion<M>> extends Model<M> implements IBean {

	public void setQuesId(java.lang.Integer quesId) {
		set("ques_id", quesId);
	}

	public java.lang.Integer getQuesId() {
		return get("ques_id");
	}

	public void setQuesType(java.lang.Integer quesType) {
		set("ques_type", quesType);
	}

	public java.lang.Integer getQuesType() {
		return get("ques_type");
	}

	public void setAnswerType(java.lang.Integer answerType) {
		set("answer_type", answerType);
	}

	public java.lang.Integer getAnswerType() {
		return get("answer_type");
	}

	public void setDifficulty(java.lang.Integer difficulty) {
		set("difficulty", difficulty);
	}

	public java.lang.Integer getDifficulty() {
		return get("difficulty");
	}

	public void setQuesStatus(java.lang.Integer quesStatus) {
		set("ques_status", quesStatus);
	}

	public java.lang.Integer getQuesStatus() {
		return get("ques_status");
	}

	public void setQuesAuditStatus(java.lang.Integer quesAuditStatus) {
		set("ques_audit_status", quesAuditStatus);
	}

	public java.lang.Integer getQuesAuditStatus() {
		return get("ques_audit_status");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("create_user");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateUser(java.lang.Integer updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.Integer getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
