package com.usejabc.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbcResourceExtend<M extends BaseAbcResourceExtend<M>> extends Model<M> implements IBean {

	public void setResId(java.lang.Integer resId) {
		set("res_id", resId);
	}

	public java.lang.Integer getResId() {
		return get("res_id");
	}

	public void setCharacterExplain(java.lang.String characterExplain) {
		set("character_explain", characterExplain);
	}

	public java.lang.String getCharacterExplain() {
		return get("character_explain");
	}

	public void setCharacterPhoneticize(java.lang.String characterPhoneticize) {
		set("character_phoneticize", characterPhoneticize);
	}

	public java.lang.String getCharacterPhoneticize() {
		return get("character_phoneticize");
	}

	public void setCharacterSideCharactor(java.lang.String characterSideCharactor) {
		set("character_side_charactor", characterSideCharactor);
	}

	public java.lang.String getCharacterSideCharactor() {
		return get("character_side_charactor");
	}

	public void setCharacterStroke(java.lang.Integer characterStroke) {
		set("character_stroke", characterStroke);
	}

	public java.lang.Integer getCharacterStroke() {
		return get("character_stroke");
	}

	public void setCharacterEnglish(java.lang.String characterEnglish) {
		set("character_english", characterEnglish);
	}

	public java.lang.String getCharacterEnglish() {
		return get("character_english");
	}

	public void setCharacterStructure(java.lang.String characterStructure) {
		set("character_structure", characterStructure);
	}

	public java.lang.String getCharacterStructure() {
		return get("character_structure");
	}

	public void setCharacterMix(java.lang.String characterMix) {
		set("character_mix", characterMix);
	}

	public java.lang.String getCharacterMix() {
		return get("character_mix");
	}

	public void setWordSegment(java.lang.String wordSegment) {
		set("word_segment", wordSegment);
	}

	public java.lang.String getWordSegment() {
		return get("word_segment");
	}

	public void setDialogAsk(java.lang.String dialogAsk) {
		set("dialog_ask", dialogAsk);
	}

	public java.lang.String getDialogAsk() {
		return get("dialog_ask");
	}

	public void setDialogAnswer(java.lang.String dialogAnswer) {
		set("dialog_answer", dialogAnswer);
	}

	public java.lang.String getDialogAnswer() {
		return get("dialog_answer");
	}

	public void setCreateUser(java.lang.Integer createUser) {
		set("create_user", createUser);
	}

	public java.lang.Integer getCreateUser() {
		return get("create_user");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdateUser(java.lang.Integer updateUser) {
		set("update_user", updateUser);
	}

	public java.lang.Integer getUpdateUser() {
		return get("update_user");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
