package com.usejabc.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("Passport_Signin_Info", "SIGNIN_ID", PassportSigninInfo.class);
		arp.addMapping("Passport_Ticket", "APP_SIGNIN_ID", PassportTicket.class);
		arp.addMapping("Passport_UserAccessLog", "AccessLogID", PassportUseraccesslog.class);
		arp.addMapping("abc_question", "ques_id", AbcQuestion.class);
		arp.addMapping("abc_question_extend", "ques_id", AbcQuestionExtend.class);
		arp.addMapping("abc_resource", "res_id", AbcResource.class);
		arp.addMapping("abc_resource_extend", "res_id", AbcResourceExtend.class);
		arp.addMapping("abc_resource_to_question", "relation_id", AbcResourceToQuestion.class);
		arp.addMapping("abc_user", "user_id", AbcUser.class);
		arp.addMapping("abc_user_answer", "answer_id", AbcUserAnswer.class);
		arp.addMapping("pt_department", "ids", PtDepartment.class);
		arp.addMapping("pt_dict", "ids", PtDict.class);
		arp.addMapping("pt_group", "ids", PtGroup.class);
		arp.addMapping("pt_grouprole", "ids", PtGrouprole.class);
		arp.addMapping("pt_menu", "ids", PtMenu.class);
		arp.addMapping("pt_module", "ids", PtModule.class);
		arp.addMapping("pt_operator", "ids", PtOperator.class);
		arp.addMapping("pt_param", "ids", PtParam.class);
		arp.addMapping("pt_resources", "ids", PtResources.class);
		arp.addMapping("pt_role", "ids", PtRole.class);
		arp.addMapping("pt_roleoperator", "ids", PtRoleoperator.class);
		arp.addMapping("pt_station", "ids", PtStation.class);
		arp.addMapping("pt_stationoperator", "ids", PtStationoperator.class);
		arp.addMapping("pt_syslog", "ids", PtSyslog.class);
		arp.addMapping("pt_systems", "ids", PtSystems.class);
		arp.addMapping("pt_upload", "ids", PtUpload.class);
		arp.addMapping("pt_user", "ids", PtUser.class);
		arp.addMapping("pt_usergroup", "ids", PtUsergroup.class);
		arp.addMapping("pt_userinfo", "ids", PtUserinfo.class);
		arp.addMapping("test_blog", "ids", TestBlog.class);
	}
}

