package com.usejabc.model;

import com.usejabc.model.base.BaseAbcQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbcQuestion extends BaseAbcQuestion<AbcQuestion> {
	public static final AbcQuestion dao = new AbcQuestion();
}
