package com.usejabc.model;

import com.usejabc.model.base.BaseAbcQuestionExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbcQuestionExtend extends BaseAbcQuestionExtend<AbcQuestionExtend> {
	public static final AbcQuestionExtend dao = new AbcQuestionExtend();
}
