package com.usejabc.model;

import com.usejabc.model.base.BaseAbcResourceExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbcResourceExtend extends BaseAbcResourceExtend<AbcResourceExtend> {
	public static final AbcResourceExtend dao = new AbcResourceExtend();
}
