package com.usejabc.model;

import com.usejabc.model.base.BaseAbcResourceToQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbcResourceToQuestion extends BaseAbcResourceToQuestion<AbcResourceToQuestion> {
	public static final AbcResourceToQuestion dao = new AbcResourceToQuestion();
}
