package com.usejabc.model;

import com.usejabc.model.base.BaseAbcResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbcResource extends BaseAbcResource<AbcResource> {
	public static final AbcResource dao = new AbcResource();
}
