package com.usejabc.model;

import com.usejabc.model.base.BaseAbcUserAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AbcUserAnswer extends BaseAbcUserAnswer<AbcUserAnswer> {
	public static final AbcUserAnswer dao = new AbcUserAnswer();
}
