package com.usejabc.model;

import java.util.UUID;

import com.usejabc.model.PassportSigninInfo;
import com.usejabc.model.AbcUser;
import com.usejabc.model.base.BasePassportSigninInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PassportSigninInfo extends BasePassportSigninInfo<PassportSigninInfo> {
	public static final PassportSigninInfo dao = new PassportSigninInfo();
	
	public PassportSigninInfo persistentSignIn(AbcUser userInfo, boolean bDontSaveUserId, boolean bAutoSignIn){
        
		String id = UUID.randomUUID().toString();
		dao.set("SIGNIN_ID", id)
		.set("USER_ID", userInfo.getUserId())
		.set("USER_NAME", userInfo.currentLoginName)
		.set("AUTHENTICATE_SERVER", userInfo.authServer)
		.save();
		
		return dao.findById(id);
	}
}
