package com.usejabc.model;

import com.usejabc.model.base.BasePtDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtDepartment extends BasePtDepartment<PtDepartment> {
	public static final PtDepartment dao = new PtDepartment();
}
