package com.usejabc.model;

import com.usejabc.model.base.BasePtDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtDict extends BasePtDict<PtDict> {
	public static final PtDict dao = new PtDict();
}
