package com.usejabc.model;

import com.usejabc.model.base.BasePtGrouprole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtGrouprole extends BasePtGrouprole<PtGrouprole> {
	public static final PtGrouprole dao = new PtGrouprole();
}
