package com.usejabc.model;

import com.usejabc.model.base.BasePtGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtGroup extends BasePtGroup<PtGroup> {
	public static final PtGroup dao = new PtGroup();
}
