package com.usejabc.model;

import com.usejabc.model.base.BasePtMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtMenu extends BasePtMenu<PtMenu> {
	public static final PtMenu dao = new PtMenu();
}
