package com.usejabc.model;

import com.usejabc.model.base.BasePtModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtModule extends BasePtModule<PtModule> {
	public static final PtModule dao = new PtModule();
}
