package com.usejabc.model;

import com.usejabc.model.base.BasePtOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtOperator extends BasePtOperator<PtOperator> {
	public static final PtOperator dao = new PtOperator();
}
