package com.usejabc.model;

import com.usejabc.model.base.BasePtParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtParam extends BasePtParam<PtParam> {
	public static final PtParam dao = new PtParam();
}
