package com.usejabc.model;

import com.usejabc.model.base.BasePtResources;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtResources extends BasePtResources<PtResources> {
	public static final PtResources dao = new PtResources();
}
