package com.usejabc.model;

import com.usejabc.model.base.BasePtRoleoperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtRoleoperator extends BasePtRoleoperator<PtRoleoperator> {
	public static final PtRoleoperator dao = new PtRoleoperator();
}
