package com.usejabc.model;

import com.usejabc.model.base.BasePtRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtRole extends BasePtRole<PtRole> {
	public static final PtRole dao = new PtRole();
}
