package com.usejabc.model;

import com.usejabc.model.base.BasePtStation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtStation extends BasePtStation<PtStation> {
	public static final PtStation dao = new PtStation();
}
