package com.usejabc.model;

import com.usejabc.model.base.BasePtStationoperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtStationoperator extends BasePtStationoperator<PtStationoperator> {
	public static final PtStationoperator dao = new PtStationoperator();
}
