package com.usejabc.model;

import com.usejabc.model.base.BasePtSyslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtSyslog extends BasePtSyslog<PtSyslog> {
	public static final PtSyslog dao = new PtSyslog();
}
