package com.usejabc.model;

import com.usejabc.model.base.BasePtSystems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtSystems extends BasePtSystems<PtSystems> {
	public static final PtSystems dao = new PtSystems();
}
