package com.usejabc.model;

import com.usejabc.model.base.BasePtUpload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtUpload extends BasePtUpload<PtUpload> {
	public static final PtUpload dao = new PtUpload();
}
