package com.usejabc.model;

import com.usejabc.model.base.BasePtUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtUserinfo extends BasePtUserinfo<PtUserinfo> {
	public static final PtUserinfo dao = new PtUserinfo();
}
