package com.usejabc.model;

import com.usejabc.model.base.BasePtUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtUser extends BasePtUser<PtUser> {
	public static final PtUser dao = new PtUser();
}
