package com.usejabc.model;

import com.usejabc.model.base.BasePtUsergroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PtUsergroup extends BasePtUsergroup<PtUsergroup> {
	public static final PtUsergroup dao = new PtUsergroup();
}
