package com.usejabc.model;

import com.usejabc.model.base.BaseTestBlog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestBlog extends BaseTestBlog<TestBlog> {
	public static final TestBlog dao = new TestBlog();
}
